dependencies {
    compileOnly("org.jetbrains:annotations:24.1.0")

    // kotlin
    runtimeOnly(forge.kotlinforforge)
    compileOnly(forge.kotlinforforge)
    api(forge.kotlinforforge)
    jarJar(forge.kotlinforforge)

    // Direct Cross-Module Source Dependency to gtm-reborn
    implementation(project(':modules:gtm-reborn')) {
        transitive = false
    }
    compileOnly(project(':modules:gtm-reborn').sourceSets.main.output)

    modCompileOnly(forge.ldlib)

    // Shimmer
    modCompileOnly(forge.shimmer)

    // Registrate
    modCompileOnly(forge.registrate)

    // Create and its dependencies
    modCompileOnly(variantOf(forge.create) { classifier("all") })
    modCompileOnly(forge.flywheel.forge)
    modCompileOnly(forge.ponder)

    // Recipe Viewers
    modCompileOnly(forge.bundles.jei)
    modCompileOnly(forge.bundles.rei)
    modCompileOnly(forge.emi)

    // Jade
    modCompileOnly(forge.jade)

    // Mixin (& Extras)
    annotationProcessor(variantOf(libs.mixin) { classifier("processor") })
    api(annotationProcessor(forge.mixinExtras.common.get()))

    // Configuration
    modCompileOnly(forge.configuration)

    // ae2
    modCompileOnly(forge.ae2)

    // AdAstra
    modCompileOnly(forge.adastra)
    modCompileOnly(forge.resourcefullib)
    modCompileOnly(forge.resourcefulconfig)
    modCompileOnly(forge.botarium)

    //others
    modCompileOnly(forge.supplementaries)
    modCompileOnly(forge.cc.tweaked.forge.impl)
    modCompileOnly(forge.selene)
    modCompileOnly(forge.botania)
    modCompileOnly(forge.curios)
    modCompileOnly(forge.patchouli)
}