dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'

    // kotlin
    runtimeOnly "thedarkcolour:kotlinforforge:4.20.0"
    compileOnly("thedarkcolour:kotlinforforge:4.20.0")
    modApi("thedarkcolour:kotlinforforge:4.20.0") { transitive = false }
    jarJar("thedarkcolour:kotlinforforge:4.20.0")

    // LDLib
    modImplementation(forge.ldlib.forge) { transitive = false }

    // Registrate
    modImplementation("com.tterrag.registrate:Registrate:${forge.versions.registrate.get()}")

    // Create and its dependencies
    modImplementation("com.simibubi.create:create-${libs.versions.minecraft.get()}:${forge.versions.createForge.get()}:all") { transitive = false }
    modImplementation forge.flywheel

    // JEI
    modCompileOnly(forge.jei.common.api) { transitive = false }
    modCompileOnly(forge.jei.forge.api) { transitive = false }
    modImplementation(forge.jei.forge.impl) { transitive = false }

    // REI
    modCompileOnly forge.rei.plugin
    modCompileOnly forge.rei.api
    modCompileOnly forge.rei.forge

    // EMI
    modCompileOnly("dev.emi:emi-forge:${forge.versions.emi.get()}:api")
    modImplementation forge.emi

    // Jade
    modImplementation(forge.jade)

    // Mixin Extras
    api(annotationProcessor("io.github.llamalad7:mixinextras-common:${this.forge.versions.mixinextras.get()}"))
    implementation("io.github.llamalad7:mixinextras-forge:${this.forge.versions.mixinextras.get()}")
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'

    // Configuration
    modImplementation(forge.configuration)

    // Shimmer
    modCompileOnly(forge.shimmer.forge) { transitive = false }

    // GTM
    modImplementation(forge.gtm) { transitive = false }

    // ae2
    modImplementation(forge.ae2) { transitive = false }

    // AdAstra
    modImplementation(forge.ad.astra) { transitive = false }
    modImplementation(forge.resourcefullib) { transitive = false }
    modImplementation(forge.resourcefulconfig)
    modImplementation(forge.botarium)
    modExtraRuntimeOnly("com.teamresourceful:ByteCodecs:1.0.2")
    modExtraRuntimeOnly("com.teamresourceful:yabn:1.0.3")

    // lib
    //jarJar(modImplementation("org.arbor:arbormixin:1.0"))

    // test
    // modImplementation("maven.modrinth:gtnn:1.0.6c")

    //others
    modImplementation("curse.maven:supplementaries-412082:5340612")
    modImplementation("curse.maven:cc-tweaked-282001:5118388")
    modExtraRuntimeOnly("cc.tweaked:cobalt:0.9.1")
    modImplementation("curse.maven:selene-499980:5361081")
    //modImplementation("com.cobblemon:forge:1.5.0+")
    //modImplementation("curse.maven:ascension-megamons-971821:5336649")
    //modRuntimeOnly("curse.maven:observable-509575:5080064")
    //modRuntimeOnly("curse.maven:architectury-api-419699:5137938")
    modImplementation("curse.maven:botania-225643:5594997")
    modImplementation("curse.maven:curios-309927:5367944")
    modImplementation("curse.maven:patchouli-306770:4966125")
}