org.gradle.jvmargs=-Xmx3G

# Mod Info
mod_id=gtnn
mod_name=GT--
mod_version=1.1.14
mod_description=Add Machines, harder recipes and many more things.
mod_license=MIT
mod_url = https://github.com/Arborsm/GT--
mod_issue_tracker = https://github.com/Arborsm/GT--/issues/

# archives_base_name=gt--
maven_group=dev.arbor
mod_authors=Arbor

enabled_platforms=forge
loom.platform=forge
