[versions]
forge = "47.3.0"
minecraftForge = "1.20.1-47.3.0"
parchment = "2023.09.03"  # https://parchmentmc.org/docs/getting-started
minecraft = "1.20.1"
spotless = "7.0.2"
modDevGradleLegacy = "2.0.95"
kotlin = "2.1.20"
kotlin-plugin = "2.1.20"
mixin = "0.8.7"

[libraries]
minecraft               = { module = "com.mojang:minecraft", version.ref = "minecraft" }
minecraftForge          = { module = "net.minecraftforge:forge", version.ref = "minecraftForge" }
mixin                   = { module = "org.spongepowered:mixin", version.ref = "mixin" }

[plugins]
spotless                = { id = "com.diffplug.spotless", version.ref = "spotless" }
modDevGradle            = { id = "net.neoforged.moddev.legacyforge", version.ref = "modDevGradleLegacy" }
kotlin-jvm              = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin           = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-plugin" }