{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-4.20.0.jar",
          "url": "kfflib-4.20.0.jar",
          "size": 41658,
          "sha512": "79ed0ae1320a7432ef8d7d2b007679d4bbf3b2a4d95d8a47d2a2bb26495c9693daf211c03b402f97d255fafb92927da975c2d4ad51c7013b0e22873bc4deb0b0",
          "sha256": "37d471f34b30254be0a8ddfa9faff8238944eda0d9d0465e7e47038dbebe413c",
          "sha1": "19d0d155bb5fc5fecfd5c1aa5830048dc9427acf",
          "md5": "aa99ca8ec82064355ed47bb92ece1169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-4.20.0.jar",
          "url": "kfflib-4.20.0.jar",
          "size": 41658,
          "sha512": "79ed0ae1320a7432ef8d7d2b007679d4bbf3b2a4d95d8a47d2a2bb26495c9693daf211c03b402f97d255fafb92927da975c2d4ad51c7013b0e22873bc4deb0b0",
          "sha256": "37d471f34b30254be0a8ddfa9faff8238944eda0d9d0465e7e47038dbebe413c",
          "sha1": "19d0d155bb5fc5fecfd5c1aa5830048dc9427acf",
          "md5": "aa99ca8ec82064355ed47bb92ece1169"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-4.20.0-sources.jar",
          "url": "kfflib-4.20.0-sources.jar",
          "size": 12564,
          "sha512": "b8f02a6d09eb9b6dde63c94d05870c1c5903bb90d7399b37b672481e0dec39bf486dac3c507c62f965d218d8509bcbf3d8479742ea511d82d2c63bc28e602ddd",
          "sha256": "5fada2689d60c16d4dddb8bf900672a5488a626d078740ada587e17b718d6808",
          "sha1": "ef8d7a4e71239be7ce5bd6ec2bb19c5b0aa1b11d",
          "md5": "a05d17e8f8ca2e8aa64799f4dae286a4"
        }
      ]
    }
  ]
}
