{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-4.20.0.jar",
          "url": "kfflang-4.20.0.jar",
          "size": 23510,
          "sha512": "61e272df049e79f04d1ea00dcc1bb26643a05998ea6b848d6462b0dcbddd574710b8274d354e29ac4c0710047d5c4ab8e0b2b9cab6b25a67c56ad0016491fac8",
          "sha256": "412986fe83bbb980034451e41a070094f706a7ff8d25382e77f18b8430cff906",
          "sha1": "e943c1957a69780204abdb540e511058cceafb7d",
          "md5": "d7e43aa694cdc87d9119cc2f2b1c37e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflang-4.20.0.jar",
          "url": "kfflang-4.20.0.jar",
          "size": 23510,
          "sha512": "61e272df049e79f04d1ea00dcc1bb26643a05998ea6b848d6462b0dcbddd574710b8274d354e29ac4c0710047d5c4ab8e0b2b9cab6b25a67c56ad0016491fac8",
          "sha256": "412986fe83bbb980034451e41a070094f706a7ff8d25382e77f18b8430cff906",
          "sha1": "e943c1957a69780204abdb540e511058cceafb7d",
          "md5": "d7e43aa694cdc87d9119cc2f2b1c37e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-4.20.0-sources.jar",
          "url": "kfflang-4.20.0-sources.jar",
          "size": 7476,
          "sha512": "876c90457daa920ee3bba7aaf1a1fc81c0493141a9354f132ae5516a83bd109321bb61d1f48a58816676d8a428669936f254c60546f71b4d3b16c60aecad6646",
          "sha256": "941188a056e4646d0664ba45638cded3d58a4166b9630ee3f416b441e318374b",
          "sha1": "06e779eb651ab6ba862973e8378fe1ab86d2d581",
          "md5": "6b995c281a0fcf527bbc31e21519cab1"
        }
      ]
    }
  ]
}
